__version__ = "1.1.3"

from pymc3_models.models.HierarchicalLogisticRegression import HierarchicalLogisticRegression
from pymc3_models.models.LinearRegression import LinearRegression
from pymc3_models.models.GaussianProcessRegression import GaussianProcessRegression
from pymc3_models.models.SparseGaussianProcessRegression import SparseGaussianProcessRegression
from pymc3_models.models.StudentsTProcessRegression import StudentsTProcessRegression


